name: install-and-test-workflow

on: [push]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install dependencies
        run: |
          uv pip install --upgrade pip
          uv pip install '.[dev]' --index-url https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple
          uv pip install coverage coveralls
      - name: Test with pytest
        run: |
          python -m coverage run -m pytest -sv
      - name: Submit to coveralls
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
      # - name: Test with nomad
      #   run: |
      #     python -m nomad.cli parse tests/data/example.archive.json

  build-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Build the package
        run: |
          uv pip install --upgrade pip
          uv pip install build
          uv python -m build --sdist
      - name: Install the package
        run: |
          uv pip install dist/*.tar.gz --index-url https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple
      # - name: Test with nomad
      #   run: |
      #     python -m nomad.cli parse tests/data/example.archive.json

  ruff-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: "check ."

  # to enable auto-formatting check, uncomment the following lines below
  ruff-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: "format . --check"
